package drools.order;

import com.sample.drools.pojo.Order;

rule "score1"
    when
        $order: Order(amount<100)
    then
        $order.setScore(0);
        System.out.println("default 0");
    end

rule "score2"
    when
        $order: Order(amount>=100 && amount<500)
    then
        $order.setScore(100);
        System.out.println("add 100");
    end

rule "score3"
    when
        $order: Order(amount>500 && amount<=1000)
    then
        $order.setScore(500);
        System.out.println("add 500");
    end

rule "score5"
    when
        $order: Order(amount>1000)
    then
        $order.setScore(1000);
        System.out.println("add 1000");
    end
