rule "simple1"
    date-effective "2022-02-15"
    when
        eval(true);
    then
        System.err.println("simple1: date-effective syntax");
end

rule "simple2"
    activation-group "active"
    when
        eval(true);
    then
        System.err.println("simple2: active-1");
end

rule "simple3"
    salience 1
    activation-group "active"
    when
        eval(true);
    then
        System.err.println("simple3: active-2");
end
