package drools.other;

import com.sample.drools.pojo.Person;

global java.util.List gList;

rule "other1"
    when
        eval(true);
    then
        gList.add("hello world");
        System.err.println("other1: global syntax");
end

query "query1"
    $person: Person(age >= 30)
end

query "query2" (String nameParam)
    $person: Person(age >= 30, name == nameParam)
end

// advanced syntax:
// - package
// - import
// - global
// - query
// - function
// - rule end
